export const SHOW_POKEMONS = 'SHOW_POKEMONS';
export const SEARCH_POKEMON = 'SEARCH_POKEMON';
export const ORDER_ASCENDING = 'ORDER_ASCENDING';
export const ORDER_DESCENDING = 'ORDER_DESCENDING';
export const ORDER_ASCENDING_ATTACK = 'ORDER_ASCENDING_ATTACK';
export const ORDER_DESCENDING_ATTACK = 'ORDER_DESCENDING_ATTACK';
export const TYPES_POKEMON = 'TYPES_POKEMON';
export const POKE_POST = 'POKE_POST';
export const POKEMONS_DETAIL = 'POKEMONS_DETAIL';



